# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e18784e716ed129324c95c3bd5c0470ef992711cfc389f8a8299562da8314c0aa26c62bf80da805d78404c6c67ffe8745ab8591218ea30ad3a1d886061cc0f73

test:
  secret_key_base: 3b687224ab762e229d54c05483c9cbbbe3d099260b5b39818e81a8a54590b4a78a53c030f27bdb4a958b17287b84e4b3fcef022f4866fff3c07ca4a72faadfbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
